library(Seurat)
library(harmony)
library(ggplot2)
library(tidyverse)
library(stringr)
library(viridis)
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
library(dplyr)
library(scCustomize)
library(monocle3)
FIB <- obj[, Idents(obj) %in% "FB"]
FIB <- NormalizeData(FIB, verbose = FALSE) 
FIB <- FindVariableFeatures(FIB, selection.method = 'vst', nfeatures = 2000)
FIB <- ScaleData(FIB, vars.to.regress = "percent.mt")
FIB <- RunPCA(FIB, features = VariableFeatures(object = FIB)) 
FIB <- RunHarmony(FIB, reduction = "pca", group.by.vars = "orig.ident", reduction.save = "harmony")
FIB <- RunUMAP(FIB, reduction = "harmony", dims = 1:30, reduction.name = "umap")
FIB <- FindNeighbors(FIB, dims = 1:30)
#FIB1 <- FIB
#FIB1 <- FindClusters(FIB1, resolution = seq(0.1,0.6,0.1))
#library(clustree)
#clustree(FIB1@meta.data, prefix = "RNA_snn_res.")
FIB <- FindClusters(FIB, resolution = 0.4)
DimPlot(FIB, reduction = 'umap', label = TRUE)
FeaturePlot(FIB, features = "RARRES2", reduction = "umap",pt.size = 1,order = T)
fib.markers <- FindAllMarkers(FIB, only.pos = TRUE, min.pct = 0.4, logfc.threshold = 1.5) 


